### PR TITLE
Add PHP linting

### PR DESCRIPTION
**Pull request by jrtashjian**
All PHPCS errors are resolved.
Needs review.

### CODE REVIEW

**Comment by AnthonyLedesma** [comment]
Working this one now.

**Comment by jrtashjian** [comment]
I'm not really understanding why the sniffs are failing in Travis-CI. An exclusion exists for the rule it's screaming about. @EvanHerman can you take a look at this?

**Comment by EvanHerman** [comment]
@jrtashjian I just went ahead and moved this all over to CircleCI. I think the issue was, the package we were using in travis (wp-dev-lib) wasn't recognizing our phpcs configuration file. Rather than digging into that and issuing a PR, I went ahead and just moved it all over to CircleCI.

I didn't setup Codeception on the CircleCI build because I figure we can eventually migrate over to Cypress.

Either way, I think this one is clear to merge 👍

**Comment by jrtashjian** [comment]
@EvanHerman Awesome, thank you!

**Pull request merged**
